list=["rahul","shivam","kavay","girish","rohit"]
print(list)
print(type(list))
print(len(list))
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
list.append ("saloni")
print(list)
list.pop(3)
print(list)
list[0]="jyoti"
print(list)
print("shivam" in list)
print("girish" in list)